apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s5af8o1ky-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s5af8o1ky-dotnet-basic-gitops